apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app2
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:WaailRajpoot/holidayproject.git # Replace with your GitHub repository URL
    targetRevision: main # Branch to track
    path: . # Path to the application manifests in your repo
  destination:
    server:  https://kubernetes.default.svc # Points to the in-cluster Kubernetes API
    namespace: project # Namespace to deploy your app
  syncPolicy:
    automated:
      prune: true # Automatically delete resources that are no longer defined in the repo
      selfHeal: true # Automatically sync if drift is detected
    syncOptions:
      - CreateNamespace=true # Automatically create namespace if it doesn't exist
