apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      imagePullSecrets:
        - name: dockerhub-cred
      initContainers:
        - name: seed-data
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - "npm"
            - "run"
            - "seed"
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mongoUri.secretName }}
                  key: {{ .Values.mongoUri.secretKey }}
      containers:
        - name: crud-app
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mongoUri.secretName }}
                  key: {{ .Values.mongoUri.secretKey }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
