apiVersion: v1
kind: Service
metadata:
  name: holidayproject  # Change to match the release name
  labels:
    app: holidayproject  # Change to match the release name
spec:
  selector:
    app: holidayproject  # Ensure this matches the deployment's labels
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
