replicaCount: 2

image:
  repository: waailrajpoot/demo-app2
  tag: latest
  pullPolicy: Always

mongoUri:
  secretName: mongo-uri-secret
  secretKey: mongo-uri

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"

securityContext:
  runAsUser: 1000
  runAsGroup: 3000
  fsGroup: 2000
